name: hales_gps
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0  # Biblioteca para o mapa
  latlong2: ^0.9.0  # Trabalhar com coordenadas
  http: 1.3.0  # Para buscar dados GPS de uma API
  web_socket_channel: ^2.4.0  # Se quiseres receber dados em tempo real (opcional)